# SPDX-FileCopyrightText: GSConnect Developers https://github.com/GSConnect
#
# SPDX-License-Identifier: GPL-2.0-or-later

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
