project_identifier: org.gnome.Shell.Extensions.GSConnect
files:
  - source: /po/org.gnome.Shell.Extensions.GSConnect.pot
    translation: /po/%locale%.po
    languages_mapping:
      locale:
        ar-SA: ar
        ca-ES: ca
        ca: ca
        fr: fr
        da: da
        de: de
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        nl-BE: nl_BE
        es-ES: es
        be: be
        cs: cs
        et: et
        gl: gl
        hu: hu
        it: it
        ja: ja
        lt: lt
        pl: pl
        ru: ru
        sk: sk
        sr: sr
        tr: tr
        uk: uk
        zh-CN: zh_CN
        zh-TW: zh_TW
