# SPDX-FileCopyrightText: GSConnect Developers https://github.com/GSConnect
#
# SPDX-License-Identifier: GPL-2.0-or-later

project_identifier: org.gnome.Shell.Extensions.GSConnect
files:
  - source: /po/org.gnome.Shell.Extensions.GSConnect.pot
    translation: /po/%locale%.po
    languages_mapping:
      locale:
        ar-SA: ar
        be: be
        ca-ES: ca
        ca: ca
        cs: cs
        da: da
        de: de
        es-ES: es
        et: et
        fi: fi
        fr: fr
        gl: gl
        hu: hu
        it: it
        ja: ja
        lt: lt
        nl-BE: nl_BE
        nl: nl_NL
        pl: pl
        pt-BR: pt_BR
        pt-PT: pt_PT
        ru: ru
        sk: sk
        sr: sr
        sr-CS: sr@latin
        tr: tr
        uk: uk
        zh-CN: zh_CN
        zh-TW: zh_TW
