# SPDX-FileCopyrightText: GSConnect Developers https://github.com/GSConnect
#
# SPDX-License-Identifier: GPL-2.0-or-later

[tool.black]
line-length = 80
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = 'nautilus-extension/.*\.py$'
