# SPDX-FileCopyrightText: GSConnect Developers https://github.com/GSConnect
#
# SPDX-License-Identifier: GPL-2.0-or-later

[tool.black]
line-length = 80
target-version = ['py36']
include = 'nautilus-extension/.*\.py$'
